package io.github.josemodi97.pesaflow4j.maven;

/**
 * The extra integration-example file written by {@link Pesaflow4jInitMojo}
 * for a given {@code -Dpesaflow4j.framework=...} choice. {@code null}
 * (via {@link #forFramework(String)}) for {@code plain}, which only gets
 * the placeholder properties file.
 */
final class FrameworkExample {

    final String relativePath;
    final String content;

    private FrameworkExample(String relativePath, String content) {
        this.relativePath = relativePath;
        this.content = content;
    }

    static FrameworkExample forFramework(String framework) {
        switch (framework) {
            case "servlet":
                return new FrameworkExample("pesaflow4j/PesaflowNotifyServlet.java", SERVLET_EXAMPLE);
            case "jakarta":
                return new FrameworkExample("pesaflow4j/PesaflowNotifyServlet.java", JAKARTA_EXAMPLE);
            case "spring-boot2":
                return new FrameworkExample("pesaflow4j/PesaflowPaymentListener.java", springBootExample("boot2"));
            case "spring-boot3":
                return new FrameworkExample("pesaflow4j/PesaflowPaymentListener.java", springBootExample("boot3"));
            default:
                return null;
        }
    }

    private static final String SERVLET_EXAMPLE =
            "package pesaflow4j;\n"
                    + "\n"
                    + "// Generated by pesaflow4j:init. Move this into your own package, and\n"
                    + "// replace the onSuccess/onFailure bodies below with real logic.\n"
                    + "// Requires the pesaflow4j-servlet dependency.\n"
                    + "\n"
                    + "import io.github.josemodi97.pesaflow4j.Pesaflow4jClient;\n"
                    + "import io.github.josemodi97.pesaflow4j.Pesaflow4jConfig;\n"
                    + "import io.github.josemodi97.pesaflow4j.servlet.Pesaflow4jServletWebhookHandler;\n"
                    + "import java.io.IOException;\n"
                    + "import javax.servlet.ServletException;\n"
                    + "import javax.servlet.annotation.WebServlet;\n"
                    + "import javax.servlet.http.HttpServlet;\n"
                    + "import javax.servlet.http.HttpServletRequest;\n"
                    + "import javax.servlet.http.HttpServletResponse;\n"
                    + "\n"
                    + "@WebServlet(\"/pesaflow4j/notify\")\n"
                    + "public class PesaflowNotifyServlet extends HttpServlet {\n"
                    + "\n"
                    + "    private final Pesaflow4jClient client = new Pesaflow4jClient(Pesaflow4jConfig.fromEnvironment());\n"
                    + "\n"
                    + "    private final Pesaflow4jServletWebhookHandler handler = new Pesaflow4jServletWebhookHandler(client)\n"
                    + "            .onSuccess((result, req, res) -> {\n"
                    + "                // TODO: mark the order paid, e.g.:\n"
                    + "                // orderService.markPaid(result.getReference(), result.getAmountPaid());\n"
                    + "            })\n"
                    + "            .onFailure((result, req, res) -> {\n"
                    + "                // TODO: log the rejection, e.g.:\n"
                    + "                // log.warn(\"PesaFlow4J: rejected notification - \" + result.getDescription());\n"
                    + "            });\n"
                    + "\n"
                    + "    @Override\n"
                    + "    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {\n"
                    + "        handler.handle(req, res);\n"
                    + "    }\n"
                    + "}\n";

    private static final String JAKARTA_EXAMPLE =
            "package pesaflow4j;\n"
                    + "\n"
                    + "// Generated by pesaflow4j:init. Move this into your own package, and\n"
                    + "// replace the onSuccess/onFailure bodies below with real logic.\n"
                    + "// Requires the pesaflow4j-jakarta dependency.\n"
                    + "\n"
                    + "import io.github.josemodi97.pesaflow4j.Pesaflow4jClient;\n"
                    + "import io.github.josemodi97.pesaflow4j.Pesaflow4jConfig;\n"
                    + "import io.github.josemodi97.pesaflow4j.jakarta.Pesaflow4jServletWebhookHandler;\n"
                    + "import jakarta.servlet.ServletException;\n"
                    + "import jakarta.servlet.annotation.WebServlet;\n"
                    + "import jakarta.servlet.http.HttpServlet;\n"
                    + "import jakarta.servlet.http.HttpServletRequest;\n"
                    + "import jakarta.servlet.http.HttpServletResponse;\n"
                    + "import java.io.IOException;\n"
                    + "\n"
                    + "@WebServlet(\"/pesaflow4j/notify\")\n"
                    + "public class PesaflowNotifyServlet extends HttpServlet {\n"
                    + "\n"
                    + "    private final Pesaflow4jClient client = new Pesaflow4jClient(Pesaflow4jConfig.fromEnvironment());\n"
                    + "\n"
                    + "    private final Pesaflow4jServletWebhookHandler handler = new Pesaflow4jServletWebhookHandler(client)\n"
                    + "            .onSuccess((result, req, res) -> {\n"
                    + "                // TODO: mark the order paid, e.g.:\n"
                    + "                // orderService.markPaid(result.getReference(), result.getAmountPaid());\n"
                    + "            })\n"
                    + "            .onFailure((result, req, res) -> {\n"
                    + "                // TODO: log the rejection, e.g.:\n"
                    + "                // log.warn(\"PesaFlow4J: rejected notification - \" + result.getDescription());\n"
                    + "            });\n"
                    + "\n"
                    + "    @Override\n"
                    + "    protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {\n"
                    + "        handler.handle(req, res);\n"
                    + "    }\n"
                    + "}\n";

    private static String springBootExample(String bootPackage) {
        return "package pesaflow4j;\n"
                + "\n"
                + "// Generated by pesaflow4j:init. Move this into your own package, and\n"
                + "// replace the TODOs below with real logic. Requires\n"
                + "// pesaflow4j-spring-" + bootPackage + "-starter and pesaflow4j.webhook.enabled=true\n"
                + "// (already added to pesaflow4j.properties by this same init run).\n"
                + "\n"
                + "import io.github.josemodi97.pesaflow4j.spring." + bootPackage + ".Pesaflow4jPaymentRejectedEvent;\n"
                + "import io.github.josemodi97.pesaflow4j.spring." + bootPackage + ".Pesaflow4jPaymentVerifiedEvent;\n"
                + "import org.springframework.context.event.EventListener;\n"
                + "import org.springframework.stereotype.Component;\n"
                + "\n"
                + "@Component\n"
                + "public class PesaflowPaymentListener {\n"
                + "\n"
                + "    @EventListener\n"
                + "    public void onPaid(Pesaflow4jPaymentVerifiedEvent event) {\n"
                + "        // TODO: mark the order paid, e.g.:\n"
                + "        // orderService.markPaid(event.getResult().getReference(), event.getResult().getAmountPaid());\n"
                + "    }\n"
                + "\n"
                + "    @EventListener\n"
                + "    public void onRejected(Pesaflow4jPaymentRejectedEvent event) {\n"
                + "        // TODO: log the rejection, e.g.:\n"
                + "        // log.warn(\"PesaFlow4J: rejected notification - \" + event.getResult().getDescription());\n"
                + "    }\n"
                + "}\n";
    }
}
